baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Dockimentation"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/sboistel/docki/tree/gohugo/content/"
  description = "My knowledge based arrount previous experiences"
  author = "sboistel"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/sboistel/docki"
weight = 10
