site_name: Dockimentation
nav:
        - Home: README.md
        - Database: 
                - Cloudera: bdd/cloudera.md
                - Hadoop: bdd/hadoop.md
                - MySQL: bdd/mysql.md
                - Oracle: bdd/oracle.md

        - Cloud: 
                - cloud/cloud_infrastructure.md
                - Amazon Web Services: cloud/aws.md
                - Google Cloud Platform: cloud/gcp.md
                - Microsoft Azure: cloud/mz.md
                - Oracle Cloud Infrastructure: cloud/oci.md

        - DevOPS: 
                - Ansible: dev/Ansible/ansible.md
                - Terraform: dev/containers/terraform.md
                - Containers: dev/containers/Docker-&-Kubernetes.md
        
        - Code:
                - Git: dev/code/Git.md
                - Perl: dev/code/Perl.md
                - Python: dev/code/Python.md
 
        - Supervision:
                - Centreon: monitoring/centreon.md
                - Nagios: monitoring/nagios.md
                - ELK: monitoring/elk.md
        - Hypervision:
                - Proxmox-VE: monitoring/pve.md
                - KVM: monitoring/kvm.md
                - VMware ESXi: monitoring/esxi.md

        - Application:
                - Account Manager: application/account_manager.md
                - Guacamole: application/guacamole.md
                - Automation: 
                        - UI-Path: application/ui-path.md
                - Bareos: application/bareos.md
                - Netbox: application/netbox.md

        - Remote:
                - VNC: application/vnc.md

        - Network: 
                - OpenVPN: application/openvpn.md

        - Operating System:
                - Linux: 
                        - System: os/linux/system.md
                        - Desktop environement: os/linux/desktop-environement.md
                        - Packages: os/linux/packages.md
                        - Analyses: os/linux/analyse.md
                        - Regular Parsing: os/linux/regular-parsing.md
                        - Application:
                                - VIM: os/linux/vim.md

                - Windaub: 
                        - Account: os/windows/account.md
                        - System:
                                - System: os/windows/sys.md
                                - boot: os/windows/boot.md
                                - Disk: os/windows/dsk.md
                        - Application & Features:
                                - WSL: os/windows/wsl.md
                                - Google Chrome: os/windows/chrome.md
                        
        
        - About: about.md
theme: readthedocs
