# Project information
site_name: Dockimentation
site_url: https://sboistel.github.io/docki/
site_author: BOISTEL Samuel
site_description: >-
  Collection of documentations wrote arround metted topics
  from my begening

# Repository
repo_name: docki
repo_url: https://github.com/sboistel/docki

# Copyright
copyright: Copyright &copy; 2023 sboistel

# Customisation
theme:
  name: material
  logo: ressources/storytelling.png
  favicon: ressources/storytelling.png
  navigation_depth: 5
  style_external_links: true

  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
# Extentions
markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes # https://python-markdown.github.io/extensions/footnotes/
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  # - optionalConfig.js
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  # - extra-loader.js

##################

# Page tree
nav:
  - Linux:
    - linux/index.md
    - linux/exit-codes.md
    - linux/regular-expressions.md
    - ACL:
        - linux/account.md
    - System:
      - linux/cron.md
      - linux/disk.md
      - linux/fstab.md
      - linux/memory.md
      - linux/proc.md
      - linux/logfile.md
    - Environment:
      - linux/desktop.md
      - linux/keymaps.md
    - App & Services:
      - linux/apps.md
      - linux/package-manager.md
      - linux/time.md
      - linux/web.md
      - linux/service.md
      - linux/smtp.md
    - Net & Sec:
      - linux/network.md
      - linux/firewalld.md
      - linux/selinux.md
    - Toolkit:
      - linux/kickstart.md
      - linux/vim.md
      - linux/gawk.md
      - linux/getops.md
      - linux/stratis.md
      - linux/screen.md
    - Rescue:
      - linux/root-rescue.md
      - linux/sar.md
    - Certification:
      - linux/rhel-sysadmin-II.md
  - Windows:
    - windows/index.md
    - windows/account.md
    - windows/apps.md
    - windows/kms.md
    - windows/powershell.md
    - windows/storage.md
    - windows/terminal.md
    - windows/vars-env.md
    - windows/windows-boot.md
    - windows/windows-system.md
    - windows/wsl.md
  - MacOS:
    - mac/index.md
    - mac/cheatsheet.md
    - mac/clipboard-manager.md
    - mac/dock.md
    - mac/ds_store.md
    - mac/iterm2.md
    - mac/package-manager.md
    - mac/remote-session.md
    - mac/screenshots.md
    - mac/sensors.md
    - mac/shurtcuts.md
    - mac/vmachines.md
    - mac/windows-tilling.md
    - mac/keybinds.md
  - DevOPS:
    - dev/index.md
    - ELK: dev/elastik.md
    - dev/docker.md
    - dev/git.md
    - dev/kubernetes.md
    - dev/multipass.md
    - dev/perl.md
    - Red Hat:
      - dev/redhat/tower-cli.md
      - dev/redhat/awx.md
    - Hashicorp:
      - dev/hashicorp/ansible.md
      - dev/hashicorp/packer.md
      - dev/hashicorp/vagrant.md
      - Terraform:
        - dev/hashicorp/terraform/index.md
        - dev/hashicorp/terraform/graph.md
        - dev/hashicorp/terraform/modules.md
        - dev/hashicorp/terraform/providers.md
        - dev/hashicorp/terraform/remote-exec.md
        - dev/hashicorp/terraform/setup.md 
        - dev/hashicorp/terraform/syntax.md
        - dev/hashicorp/terraform/tfstate.md
        - dev/hashicorp/terraform/vars.md
    - Python: 
        - dev/python/index.md
        - dev/python/dict.md
        - dev/python/comparators.md
        - dev/python/lists.md
        - dev/python/loop.md
        - dev/python/venv.md
        - dev/python/tkinter.md
        - More:
            - dev/python/more/index.md
            - dev/python/more/dictionaries.md
            - dev/python/more/reading-and-writing-files.md
            - dev/python/more/built-in-functions.md
            - dev/python/more/exception-handling.md
            - dev/python/more/string-formatting.md
            - dev/python/more/args-and-kwargs.md
            - dev/python/more/virtual-environments.md
            - dev/python/more/dataclasses.md
            - dev/python/more/file-directory-path.md
            - dev/python/more/sets.md
            - dev/python/more/main.md
            - dev/python/more/context-manager.md
            - dev/python/more/json-yaml.md
            - dev/python/more/manipulating-strings.md
            - dev/python/more/oop-basics.md
            - dev/python/more/functions.md
            - dev/python/more/control-flow.md
            - dev/python/more/comprehensions.md
            - dev/python/more/debugging.md
            - dev/python/more/regular-expressions.md
            - dev/python/more/lists-and-tuples.md
            - dev/python/more/setup-py.md
  - Monitoring:
    - monitoring/index.md
    - monitoring/centreon.md
    - monitoring/nagios.md
  - Tools:
    - tool/index.md
    - tool/freeipa.md
    - tool/guacamole.md
    - tool/netbox.md
    - tool/pi-hole.md
    - tool/rhel_idm.md
    - tool/rundeck.md
    - tool/sshs.md
    - tool/ui-path.md
    - tool/vnc-tiger.md
    - tool/vscode.md
    - tool/wikijs.md
  - Web & Networking:
    - network/index.md
    - network/certmanager.md
    - network/homeassistant.md
    - network/mkcert.md
    - network/ssl.md
    - network/http-status.md
    - network/openvpn.md
    - network/performance.md
    - network/ngrok.md
    - network/pi-hole.md
  - Cloud & Hypervisor:
    - cloud/index.md
    - cloud/aws.md
    - cloud/awx.md
    - cloud/azure.md
    - cloud/cgp.md
    - cloud/oci.md
    - cloud/vmware.md
    - cloud/pve.md
    - cloud/kvm.md
    - Certification:
      - cloud/az-104.md
  - Storage & BDD:
    - storage/bareos.md
    - storage/cloudera.md
    - storage/hadoop.md
    - storage/oracle.md
    - storage/mysql.md
    - storage/db2.md
    - storage/mariadb.md
  - Miscellaneous:
    - misc/color-codes.md
    - misc/markdown.md
    - misc/mkdocs.md
    - misc/mermaid.md
    - misc/obsidian.md
