site_name: Dockimentation
site_description: Docki wiki github pages
site_author: BOISTEL Samuel

nav:
        - Home: README.md

        - Linux: Linux

        - Windows:
                - Windows.md
                - Windows-Terminal.md
                - wsl.md
        
        - Cloud:
                - Cloud_Infrastructure.md
                - Amazon_Web_Services.md
                - Azure_Cloud.md
                - Google_Cloud_Platforme.md
                - Oracle_Cloud_Infrastructure.md

        - Networking:
                - CertManager.md
        
        - Hypervisor:
                - Monitoring.md
                - VMware.md
                - Proxmox-VE.md
                - QEMU-KVM.md
        
        - Tools:
                - Centreon_Central.md
                - Nagios.md
                - Netbox.md
                - Rhel_IDM.md
                - Guacamole.md
                - UI-path.md
                - VNC_Tiger.md
                - OpenVPN.md
                - Markdown.md
                - Ngrok.md
        
        - Storage:
                - Bareos.md
        
        - BDD/BigData:
                - Cloudera.md
                - Hadoop.md
                - Oracle.md
                - MySQL.md
                - DB2.md
                - MariaDB.md
        
        - DevOPS:
                - Ansible_Engine.md
                - Docker.md
                - ELastiK.md
                - FreeIPA.md
                - Terraform.md
                - Kubernetes.md
                - Git.md
                - Perl.md
                - Python.md

theme: 
  name: material
  navigation_depth: 2