site_name: Dockimentation
nav:
        - Home: README.md
        - Database: bdd/readme.md
        - Cloud: cloud/readme.md
        - DevOPS: dev/readme.md
        - Containers: dev/containers/readme.md
        - Monitoring: monitoring/readme.md
        - Application: application/readme.md
        - Linux: os/linux/readme.md
        - Windaub: os/windows/readme.md
        - About: about.md
theme: readthedocs
