# Project information
site_name: Dockimentation
site_url: https://sboistel.github.io/docki/
site_author: BOISTEL Samuel
site_description: >-
  Collection of documentations wrote arround metted topics
  from my begening

# Repository
repo_name: docki
repo_url: https://github.com/sboistel/docki

# Copyright
copyright: Copyright &copy; 2022 sboistel

# Theme
theme:
  name: material
  logo: ressources/storytelling.png
  favicon: ressources/storytelling.png
  
  navigation_depth: 5
  style_external_links: true
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Page tree
nav:
  cloud:
    - cloud/aws.md
    - cloud/azure.md
    - cloud/cgp.md
    - cloud/kvm.md
    - cloud/oci.md
    - cloud/pve.md
    - cloud/readme.md
    - cloud/vmware.md
  dev:
    - dev/ansible.md
    - dev/docker.md
    - dev/elastik.md
    - dev/git.md
    - dev/kubernetes.md
    - dev/perl.md
    - dev/python.md
    - dev/terraform.md
  linux:
    - linux/account.md
    - linux/apps.md
    - linux/cron.md
    - linux/desktop.md
    - linux/disk.md
    - linux/exit-codes.md
    - linux/firewalld.md
    - linux/gawk.md
    - linux/keymaps.md
    - linux/kickstart.md
    - linux/logfile.md
    - linux/memory.md
    - linux/network.md
    - linux/package-manager.md
    - linux/proc.md
    - linux/regular-expressions.md
    - linux/root-rescue.md
    - linux/sar.md
    - linux/screen.md
    - linux/selinux.md
    - linux/service.md
    - linux/smtp.md
    - linux/stratis.md
    - linux/time.md
    - linux/vim.md
    - linux/web.md
    - linux/where.md
  mac:
    - mac/cheatsheet.md
    - mac/clipboard-manager.md
    - mac/iterm2.md
    - mac/package-manager.md
    - mac/remote-session.md
    - mac/screenshots.md
    - mac/shurtcuts.md
    - mac/vmachines.md
    - mac/windows-tilling.md
  misc:
    - misc/color-codes.md
    - misc/markdown.md
  monitoring:
    - monitoring/centreon.md
    - monitoring/nagios.md
  network:
    - network/certmanager.md
    - network/http-status.md
    - network/mkcert.md
    - network/ngrok.md
    - network/openvpn.md
    - network/ssl.md
  storage:
    - storage/bareos.md
    - storage/cloudera.md
    - storage/db2.md
    - storage/hadoop.md
    - storage/mariadb.md
    - storage/mysql.md
    - storage/oracle.md
  tool:
    - tool/freeipa.md
    - tool/guacamole.md
    - tool/netbox.md
    - tool/rhel_idm.md
    - tool/ui-path.md
    - tool/vnc-tiger.md
    - tool/vscode.md
  windows:
    - windows/account.md
    - windows/apps.md
    - windows/powershell.md
    - windows/storage.md
    - windows/terminal.md
    - windows/vars-env.md
    - windows/windows-boot.md
    - windows/windows-system.md
    - windows/wsl.md