site_name: Dockimentation
nav:
        - Home: README.md

        - Operating System: 
                - linux.md
                - windows.md
        
        - Cloud:
                - Cloud_Infrastructure.md
                - Amazon_Web_Services.md
                - Azure_Cloud.md
                - Google_Cloud_Platforme.md
                - Oracle_Cloud_Infrastructure.md
        
        - Hypervisor:
                - Monitoring.md
                - VMware.md
                - Proxmox-VE.md
                - QEMU-KVM.md
        
        - Tools:
                - Centreon_Central.md
                - Nagios.md
                - Netbox.md
                - Rhel_IDM.md
                - Guacamole.md
                - UI-path.md
                - VNC_Tiger.md
                - OpenVPN.md
                - Markdown.md
        
        - Storage:
                - Bareos.md
        
        - BDD/BigData:
                - Cloudera.md
                - Hadoop.md
                - Oracle.md
                - MySQL.md
                - db2.md
        
        - DevOPS:
                - Ansible_Engine.md
                - Docker.md
                - ELastiK.md
                - Terraform.md
                - Kubernetes.md
                - Git.md
                - Perl.md
                - Python.md

        - About: about.md
theme: readthedocs
