# Project information
site_name: Dockimentation
site_url: https://sboistel.github.io/docki/
site_author: BOISTEL Samuel
site_description: >-
  Collection of documentations wrote arround metted topics
  from my begening

# Repository
repo_name: docki
repo_url: https://github.com/sboistel/docki

# Copyright
copyright: Copyright &copy; 2022 sboistel

# Theme
theme:
  name: readthedocs
  style_external_links: true
  navigation_depth: 5

# Page tree
nav:
  - README.md
  - Linux:
    - linux/linux.md
    - linux/account.md
    - linux/apps.md
    - linux/cron.md
    - linux/desktop.md
    - linux/disk.md
    - linux/firewalld.md
    - linux/gawk.md
    - linux/linux.md
    - linux/logfile.md
    - linux/memory.md
    - linux/network.md
    - linux/smtp.md
    - linux/package-manager.md
    - linux/proc.md
    - linux/regular-expressions.md
    - linux/root-rescue.md
    - linux/sar.md
    - linux/screen.md
    - linux/selinux.md
    - linux/service.md
    - linux/stratis.md
    - linux/time.md
    - linux/vim.md
    - linux/web.md
    - linux/where.md
  - Windows:
    - Windows.md
    - Windows-Terminal.md
    - wsl.md
  - MacOS:
    - MacOS.md
    - iterm2.md
  - Code & DevOPS:
    - Perl.md
    - Python.md
    - Ansible_Engine.md
    - Docker.md
    - ELastiK.md
    - Terraform.md
    - Kubernetes.md
    - Git.md
  - Tools:
    - Centreon_Central.md
    - Nagios.md
    - Netbox.md
    - Rhel_idM.md
    - FreeIPA.md
    - Guacamole.md
    - UI-path.md
    - VNC_Tiger.md
    - OpenVPN.md
    - Ngrok.md
    - vscode.md
  - Web & Networking:
    - CertManager.md
    - mkcert.md
    - SSL.md
    - http-status.md
  - Cloud & Hypervisor:
    - Cloud_Infrastructure.md
    - Amazon_Web_Services.md
    - Azure_Cloud.md
    - Google_Cloud_Platforme.md
    - Oracle_Cloud_Infrastructure.md
    - VMware.md
    - Proxmox-VE.md
    - QEMU-KVM.md
  - Storage & BDD & BigData:
    - Bareos.md
    - Cloudera.md
    - Hadoop.md
    - Oracle.md
    - MySQL.md
    - DB2.md
    - MariaDB.md
  - Miscellaneous:
    - color-codes.md
    - Markdown.md