site_name: Dockimentation
nav:
        - Home: README.md
        - Database: 
                - bdd/Mysql.md
                - bdd/Oracle.md
        - Cloud:
                - cloud/Amazon-Web-Services.md
                - cloud/Cloud-Platformes.md
                - cloud/Google-Cloud-Platform.md
                - cloud/Microsoft-Azure.md
                - Oracle-Cloud-Infrastructure.md
        - Development:
                - Code:
                        - dev/code/Git.md
                        - dev/code/Perl.md
                        - dev/code/Python.md
                - Containers:
                        - containers/Conteneurisation.md
                        - containers/Docker-&-Kubernetes.md
                - dev/Ansible.md
                - dev/Terraform.md
        - Monitoring:
                - monitoring/Centreon.md
                - monitoring/ELK.md
                - monitoring/KVM.md
                - monitoring/Proxmox-VE.md
        - Operating System:
                - Linux:
                        - os/linux/Desktop-Environement.md
                        - os/linux/Linux
                - Windaub:
                        - os/windows/Windows.md
        - About: about.md
theme: readthedocs