site_name: Dockimentation
site_description: Docki wiki github pages
site_author: BOISTEL Samuel

nav:
        - Home: README.md

        - Linux: 
                - Linux.md
                - smtp.md
        - Windows:
                - Windows.md
                - Windows-Terminal.md
                - wsl.md
        - MacOS:
                - MacOS.md
                - iterm2.md

        - Code :
                - Perl.md
                - Python.md

        - DevOPS:
                - Ansible_Engine.md
                - Docker.md
                - ELastiK.md
                - Terraform.md
                - Kubernetes.md
                - Git.md

        - Tools:
                - Centreon_Central.md
                - Nagios.md
                - Netbox.md
                - Rhel_idM.md
                - FreeIPA.md
                - Guacamole.md
                - UI-path.md
                - VNC_Tiger.md
                - OpenVPN.md
                - Markdown.md
                - Ngrok.md
                - vscode.md

        - miscellaneous:
                - color-codes.md  

        - Web & Networking:
                - CertManager.md
                - SSL.md
                - http-status.md    
        
        - Hypervisor:
                - VMware.md
                - Proxmox-VE.md
                - QEMU-KVM.md
        
        - Storage:
                - Bareos.md

        - Cloud:
                - Cloud_Infrastructure.md
                - Amazon_Web_Services.md
                - Azure_Cloud.md
                - Google_Cloud_Platforme.md
                - Oracle_Cloud_Infrastructure.md
        
        - BDD/BigData:
                - Cloudera.md
                - Hadoop.md
                - Oracle.md
                - MySQL.md
                - DB2.md
                - MariaDB.md

theme: 
  name: readthedocs
  navigation_depth: 2
  style_external_links: true