site_name: Dockimentation
nav:
        - Home: README.md
        - Linux:
                - Linux/Linux.md
                - Linux/Account.md
                - Linux/Analyse.md
                - Linux/Applications.md
                - Linux/Desktop_Environement.md
                - Linux/Storage.md
                - Linux/System.md
                - Linux/Tools_&_Packages.md
        - Windows:
                - Windows/Windows.md
                - Windows/account.md
                - Windows/Applications.md
                - Windows/boot.md
                - Windows/Storage.md
                - Windows/System.md

        - Amazon_Web_Services.md
        - Ansible_Engine.md
        - Azure_Cloud.md
        - Bareos.md
        - Centreon_Central.md
        - Cloudera.md
        - Cloud_Infrastructure.md
        - Docker.md
        - ELastiK.md
        - Git.md
        - Google_Cloud_Platforme.md
        - Guacamole.md
        - Hadoop.md
        - IPAM_-_Netbox.md
        - Kubernetes.md
        - Monitoring.md
        - MySQL.md
        - Nagios.md
        - OpenVPN.md
        - Oracle_Cloud_Infrastructure.md
        - Oracle.md
        - Perl.md
        - Proxmox-VE.md
        - Python.md
        - QEMU-KVM.md
        - Rhel_IDM.md
        - Terraform.md
        - UI-path.md
        - VMware.md
        - VNC_Tiger.md

        - About: about.md
theme: readthedocs
