# Project information
site_name: Dockimentation
site_url: https://sboistel.github.io/docki/
site_author: BOISTEL Samuel
site_description: >-
  Collection of documentations wrote arround metted topics
  from my begening

# Repository
repo_name: docki
repo_url: https://github.com/sboistel/docki

# Copyright
copyright: Copyright &copy; 2022 sboistel

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - mkdocs_graphviz:
      light_theme: 000000      # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      dark_theme: FFFFFF       # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      color: 789ABC            # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      bgcolor: none            # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      graph_color: 789ABC      # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      graph_fontcolor: 789ABC  # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      node_color: 789ABC       # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      node_fontcolor: 789ABC   # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      edge_color: 789ABC       # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      edge_fontcolor: 789ABC   # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      priority: 75             # The priority for this Markdown Extension (DEFAULT : 75)

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js


# Theme
theme:
  name: material
  logo: ressources/storytelling.png
  favicon: ressources/storytelling.png
  
  navigation_depth: 5
  style_external_links: true
  
  features:
    # - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Page tree
nav:
  - Linux:
    - linux/readme.md
    - linux/account.md
    - linux/apps.md
    - linux/cron.md
    - linux/desktop.md
    - linux/disk.md
    - linux/exit-codes.md
    - linux/firewalld.md
    - linux/fstab.md
    - linux/gawk.md
    - linux/getops.md
    - linux/keymaps.md
    - linux/kickstart.md
    - linux/logfile.md
    - linux/memory.md
    - linux/network.md
    - linux/package-manager.md
    - linux/proc.md
    - linux/regular-expressions.md
    - linux/root-rescue.md
    - linux/sar.md
    - linux/screen.md
    - linux/selinux.md
    - linux/service.md
    - linux/smtp.md
    - linux/stratis.md
    - linux/time.md
    - linux/vim.md
    - linux/web.md
    - Certification: 
      - linux/rhel-sysadmin-II.md
  - Windows:
    - windows/readme.md
    - windows/account.md
    - windows/apps.md
    - windows/kms.md
    - windows/powershell.md
    - windows/storage.md
    - windows/terminal.md
    - windows/vars-env.md
    - windows/windows-boot.md
    - windows/windows-system.md
    - windows/wsl.md
  - MacOS:
    - mac/readme.md
    - mac/cheatsheet.md
    - mac/clipboard-manager.md
    - mac/dock.md
    - mac/ds_store.md
    - mac/iterm2.md
    - mac/package-manager.md
    - mac/remote-session.md
    - mac/screenshots.md
    - mac/shurtcuts.md
    - mac/vmachines.md
    - mac/windows-tilling.md
    - mac/keybinds.md
  - DevOPS:
    - dev/readme.md
    - dev/ansible.md
    - dev/docker.md
    - dev/elastik.md
    - dev/git.md
    - dev/kubernetes.md
    - dev/multipass.md
    - dev/packer.md
    - dev/perl.md
    - dev/python.md
    - dev/terraform.md
    - dev/tower-cli.md
    - dev/vagrant.md
  - Monitoring:
    - README: monitoring/readme.md
    - monitoring/centreon.md
    - monitoring/nagios.md
  - Tools:
    - tool/readme.md
    - tool/freeipa.md
    - tool/guacamole.md
    - tool/netbox.md
    - tool/pi-hole.md
    - tool/rhel_idm.md
    - tool/rundeck.md
    - tool/sshs.md
    - tool/ui-path.md
    - tool/vnc-tiger.md
    - tool/vscode.md
    - tool/wikijs.md
  - Web & Networking:
    - network/readme.md
    - network/certmanager.md
    - network/mkcert.md
    - network/ssl.md
    - network/http-status.md
    - network/openvpn.md
    - network/ngrok.md
    - network/pi-hole.md
  - Cloud & Hypervisor:
    - cloud/readme.md
    - cloud/aws.md
    - cloud/awx.md
    - cloud/azure.md
    - cloud/cgp.md
    - cloud/oci.md
    - cloud/vmware.md
    - cloud/pve.md
    - cloud/kvm.md
    - Certification:
      - cloud/az-104.md
  - Storage & BDD:
    - storage/bareos.md
    - storage/cloudera.md
    - storage/hadoop.md
    - storage/oracle.md
    - storage/mysql.md
    - storage/db2.md
    - storage/mariadb.md
  - Miscellaneous:
    - misc/color-codes.md
    - misc/markdown.md
    - misc/mkdocs.md
    - misc/mermaid.md
    - misc/obsidian.md