name: Build and Serve GoHugo
on:
    push:
        branches:
            - gohugo

jobs:
    build-and-serve:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
                uses: actions/checkout@v2

            - name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.17

            - name: Build GoHugo site
                run: |
                    go install github.com/gohugoio/hugo@latest
                    hugo

            - name: Serve GoHugo site
                run: hugo serve