name: Build and Serve Mkdocs
on:
  workflow_dispatch:
  push:
    branches:
    - gohugo

jobs:
  publish-gohugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull Changes
        run: git pull

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17
  
      - name: Build GoHugo site
        run: |
            go install github.com/gohugoio/hugo@latest
            hugo
  
      - name: Serve GoHugo site
        run: hugo serve
