name: publish-site
on:
  push:
    branches:
    - master

jobs:
  # Lints markdown content
  lint-code:
    runs-on: ubuntu-latest
   # Lightweight linter
   
    steps:
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v3.0.1
      with:
        files: docs/*

  publish-site:
    needs: [lint-code]
    runs-on: ubuntu-latest
    steps:
      - name: Install Mkdocs
        run: pip install mkdocs

      - name: Get latest changes
        run: git pull

      - name: Deploy site
        run: mkdocs gh-deploy