name: publish-site
on:
  push:
    branches:
    - main

jobs:
  # Lints markdown content
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Mkdocs
        run: pip install mkdocs mkdocs-material pymdown-extensions py-dot 

      - name: Lint Markdown
        run: mkdocs build --strict

  publish-site:
    needs: [lint-code]
    runs-on: ubuntu-latest
    steps:
      - name: Get latest changes
        uses: actions/checkout@v3

      - name: Deploy site
        run: mkdocs gh-deploy
