name: publish-site
on:
  push:
    branches:
    - readthedocs

jobs:
  readthedocs-cooking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull Changes
        run: git pull

      - name: Install Mkdocs
        run: pip install mkdocs mkdocs-material pymdown-extensions py-dot 

      - name: Lint Markdown
        run: mkdocs build --strict

      - name: Deploy site
        run: mkdocs gh-deploy
